### ISSUE TITLE
fix report constructor service network 4 docker deploy

### ISSUE THREAD

**Issue by hypnospinner** [dckntm/focus-backend#15]
### Requested Changes

Fix network name in docker-compose script 4 report ctor service

### Implementation Details

`rcs-network`

### Additional Info

Networks are defined usually in the end of docker compose with the following synthax:

```yml
version: "3.1"

# services there ...

  networks:
    backend: #<- this is network name which
```
